### ISSUE TITLE
[issue]: Ubuntu Unity 20.04.3 boots into grub rescue

### ISSUE THREAD

**Issue by evs-xsarus** [ventoy/Ventoy#1095]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://linux.darkpenguin.net/distros/ubuntu-unity/20.04.3/

### What happened?

The ISO showed up in the Ventoy menu but upon selecting it to boot, the machine boots into grub rescue showing:

> grub_unixtime2datetime not found

Machine: Dell Precision 7550
Host OS: Ubuntu Unity 20.04.1 with encrypted hard disk

I can boot that ISO fine; http://linux.darkpenguin.net/distros/ubuntu-unity/20.04.1/

**Comment by ventoy** [comment]
Can the iso file boot fine if you directly connect it to a VM(vmware/virtualbox/qemu) and boot in UEFI mode? ---- Replied Message ***@***.***>Date09/12/2021 22:02 ***@***.***> ***@***.***>Subject[ventoy/Ventoy] [issue]: Ubuntu Unity 20.04.3 boots into grub rescue (#1095)
Official FAQ

 I have checked the official FAQ.

Ventoy Version
1.0.51
What about latest release
Yes. I have tried the latest release, but the bug still exist.
BIOS Mode
UEFI Mode
Partition Style
MBR
Disk Capacity
32GB
Disk Manufacturer
SanDisk
Image file checksum (if applicable)
Yes.
Image file download link (if applicable)
http://linux.darkpenguin.net/distros/ubuntu-unity/20.04.3/
What happened?
The ISO showed up in the Ventoy menu but upon selecting it to boot, the machine boots into grub rescue showing:

grub_unixtime2datetime not found

Machine: Dell Precision 7550
Host OS: Ubuntu Unity 20.04.1 with encrypted hard disk
I can boot that ISO fine; http://linux.darkpenguin.net/distros/ubuntu-unity/20.04.1/

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/1095",
"url": "https://github.com/ventoy/Ventoy/issues/1095",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by evs-xsarus** [comment]
The ISO starts in both UEFI and legacy mode. Tested on VirtualBox  6.1.26_Ubuntu r145957

**Comment by steve6375** [comment]
Depends on UEFI firmware maybe?
https://www.mail-archive.com/grub-devel@gnu.org/msg32169.html
bug was fixed in later versions.

**Comment by steve6375** [comment]
Ventoy + 20.04.3 ISO fails in same way on my IdeaPad300 UEFI64  but works on VBox 3 UEFI64.
Also fails on IdeaPad300 using grubfm.

**Comment by ventoy** [comment]
Can try  press `ctrl+g` to enter grub2 mode and then select the ISO file to boot.

**Comment by steve6375** [comment]
ctrl+r on IdeaPad300 works OK

**Comment by ventoy** [comment]
So it seems an issue of the ISO file itself.
