### ISSUE TITLE
[SOLVED]: NOT working with Austrumi yet and 4MLinux

### ISSUE THREAD

**Issue by pigeonskiller** [ventoy/Ventoy#1121]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.53

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

SanDisk

### What happened?

Hi, sorry to inform you that Austrumi 4.5.2 does NOT work yet: it stops at Grub with message "Grub loading" or something similar.

Similar problem with 4MLinux 37.1: here Grub is loaded but then it stops with the command line.

Hope you solve soon.

Thanks and have a nice day.

**Comment by ventoy** [comment]
I download `austrumi64-4.5.2.iso` and it boot ok in my laptop.
So maybe the ISO file is corrupted when you copy it to the USB drive.
Please checksum it as follows:
![image](https://user-images.githubusercontent.com/59477474/136700284-e5041330-ed8c-4b37-afdf-d4f7eb8deaf9.png)

**Comment by ventoy** [comment]
Well the previous test is in Legacy BIOS mode, and in UEFI mode it can not boot.
But I think it is not Ventoy issue. Because I directly connect the `austrumi64-4.5.2.iso` to the CD/DVD with VMWARE and it can not boot at all in UEFI mode.
**So the ISO file itself has some problem, it can not boot in UEFI mode from CD/DVD.**

You can create an issue to Austrumi and hope they can fix it in the future release.

**Comment by ventoy** [comment]
Ventoy provides a `grub2 mode`, you can use as a workaround. 
Press  `ctrl+r` to enter grub2 mode and then select the ISO file to boot.
**But it should be pointed out that the most fundamental reason lies in the ISO file itself.**

**Comment by pigeonskiller** [comment]
Thank yo very much, ctrl+r

**Comment by pigeonskiller** [comment]
Thank you very much, ctrl+r worked for both distros.
