### ISSUE TITLE
[issue]: "Failed to open random seed file: write protected" with Solus Budgie installer

### ISSUE THREAD

**Issue by 190n** [ventoy/Ventoy#1211]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.58

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://mirrors.rit.edu/solus/images/4.3/Solus-4.3-Budgie.iso

### What happened?

After choosing the Solus image in Ventoy and then choosing the Solus installer from its own boot menu, I see `Failed to open random seed file: write protected`. This seems like the same issue as #764, except whatever fix worked for Arch (I have tried booting Arch with Ventoy, and it works) didn't work for Solus.

**Comment by ventoy** [comment]
It's a systemd bug, I have commit a PR to systemd and the developer has accepted this patch.
https://github.com/systemd/systemd/pull/20383

So in the future release there will no such warning. 
This just print a warning message and has no other effect.
Because it's not Ventoy issue so I don't want to make new workaround about it for new distro anymore.

**Comment by 190n** [comment]
Ah okay, thanks. I wasn't sure if the same systemd fix would apply here. And it seems like systemd hasn't had a release since that fix was merged... hopefully Solus gets it before too long. In the meantime I'll just boot the Solus installer normally. Thanks for the info.
