### ISSUE TITLE
[issue]: Write IO activity after Ventoy USB ejected

### ISSUE THREAD

**Issue by 14v** [ventoy/Ventoy#1249]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16GB

### What happened?

After I copied *.iso to the ventoy partition and ejected USB in the file manager it takes long time when "write data" notification keeps on desktop. Copying is finished fast and no matter UI or cp command used. Usually does not see such behaviour when using USB sticks. iotop shows write IO:

![image](https://user-images.githubusercontent.com/4716175/141826717-0fc80b05-0210-484e-8d7d-deb0264c0bb7.png)

**Comment by ventoy** [comment]
When the `cp` command finish, still many data is in the cache and has not been flushed to the USB stick.
It need time to fully flush the data to the USB stick.

For cross-platform compability, Ventoy format the partition (/dev/sdd1 in your case) in exFAT filesystem, and most Linux system use FUSE to mount exFAT which is much slower compared with some native filesystem (e.g. ext4/xfs...)

You can also re-format the partition (/dev/sdd1 in your case)  from exFAT to ext2/3/4 or xfs, then the write progress will be much faster. But because Windows/MacOS does not support ext2/3/4 and xfs by default. So if you do so, the USB stick will not be recognized when you plug it to a Windows/MacOS computer. 
Of cause if you only use Linux and never use Windows/MacOS, then it's OK, you can reformat it to ext2/3/4 or xfs.

**Comment by 14v** [comment]
There is no such problem when I use FAT32 USB. Does this problem occur only on exFAT?

**Comment by ventoy** [comment]
Yes. Linux kernel natively support FAT32.
As I known,  most of linux distros  use FUSE to mount `exFAT` and `NTFS`.
So this problem should occur for both exFAT and NTFS.

You can test by yourself.  
Forget Ventoy,  just use parted/gparted or other disk tools to clean the disk firstly and then create a partition and then format it in exFAT or NTFS filesystem.
After that try copy a big ISO file to this partition and see whether is has similar problem.
