### ISSUE TITLE
[issue]: 2021.3a-live-amd64-iso fails to boot with secure mode enabled on 2 different machines

### ISSUE THREAD

**Issue by gottalovebrando** [ventoy/Ventoy#1283]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

ventoy-1.0.61-windows

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

PNY

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://www.kali.org/get-kali/#kali-live

### What happened?

This version of kali won't boot. Using image **2021.3a-live-amd64-iso**. It loads GRUB (version: 2.04-20kalil) but then every selection made from the GRUB menu has an error. The default boot mode gives this error: _error: Secure boot forbids loading module from (cd0)/boot/grub/x86_64-efi/linux.mod_ and all other boot selections give the same or similar errors.

Please note this download link provided in the field above may update to a new version of kali. However, it does not yet appear to be in their archive here:http://old.kali.org/kali-images/

I thought it was worth reporting since previous images have been reported to work on the website (maybe kali changed something). This same image and USB drive work on a machine without secure boot enabled in UEFI mode and legacy. Thanks! I don't check github much but feel free to ping me for more info if needed.

This error occurred on two different machines with secure boot enabled:
Surface Go
Processor	Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz   1.61 GHz
Installed RAM	4.00 GB (3.89 GB usable)
System type	64-bit operating system, x64-based processor
Installed OS (just in case)	Windows 10 Pro

HP Pavilion Laptop 14-ce0xxx
Processor	Intel® Core™ i5-8250U CPU @ 1.60GHz × 8 
Installed RAM	15.5 GiB
System type	64-bit operating system, x64-based processor
Installed OS (just in case)	Ubuntu 20.04.3 LTS

**Comment by ventoy** [comment]
Can it boot OK if you use other tools(e.g. Rufus) to burn the same ISO to the same USB and boot in the same computer?

**Comment by ventoy** [comment]
Kali never support secure boot.  You can test the iso file with VMware (enable secure boot) and it can not boot at all.
The support in the website is tested when secure boot is disabled.

**Comment by gottalovebrando** [comment]
I have not tried any other tools, sorry. Good to know about secure boot,
sorry I missed that on kali's website. From a technical perspective, what
is needed to support secure boot? I was under the impression it was just
the GRUB (or windows) bootloader signed with a key the firmware trusts. If
that is correct, I don't see why kali couldn't just use that version of
GRUB.

The whole secure boot seems annoying because I read windows 11 will require
secure boot.

Thanks!

**Comment by ventoy** [comment]
To supported secure boot, the boot loader must be signed with a trusted key by the firmware. 
All the firmware in the mother board (no matter which Vendor) will integrate Microsoft's key because Windows is the most common used OS.
Although you can import a key to the firmware to let your bootloader trused by the firmware, but it is not so convenient and not  everyone is familiar with this operation.

So if the distro want to support secure boot perfectly, it must make its Shim signed with Microsoft's  key. 
That's just how Redhat/Ubuntu/SUSE did. But you have to abide by Microsoft's very strict rules and spend some money to let Microsoft agree to sign your Shim with their key. That's why only few Linux distros (those backed by commercial companies) support secure boot.
