### ISSUE TITLE
[issue]: Active Boot Disk 17.0 does not boot in UEFI mode

### ISSUE THREAD

**Issue by chandanps18** [ventoy/Ventoy#1367]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

SanDisk

### What happened?

A bug happened!
Active Boot Disk 17.0 does not boot with UEFI BIOS mode. However, the Legacy mode works perfectly. I checked the website and found that, there is a new version available i.e. version 18.0 of active boot disk. I did not try that.

I just want the product developer to look into this and solve the problem.

**Comment by chandanps18** [comment]
There will no reply yet.
Waiting to see any possible solution for this issue.

**Comment by ventoy** [comment]
Please test the ISO file with VM firstly(e.g. VMware or VirtualBox)
Set the VM to UEFI mode and connect the ISO file directly to the VM and boot.
If it can not boot in UEFI mode in VM then it means that the ISO file itself has some problem to boot in UEFI mode.

**Comment by chandanps18** [comment]
Hello,
I have tested the file in uefi and legacy mode in the computer. It is working fine.

Anyhow, as per your suggestion I will not the ISO in VMware and post reply here....

Thank you

**Comment by ventoy** [comment]
I download a Active Boot Disk 17.0 ISO file and it can not boot in VMWare in UEFI mode from CD/DVD.

**Comment by chandanps18** [comment]
Yes,
I checked with vmware as well. It is not working.
But if I make a Bootable USB device of this ISO by using rufus, it works perfectly...

Hope, you can find any workaround to boot it properly. 
Or else, it is confirmed that, Active boot Disk 17.0 does not support booting in uefi mode with ventoy.

**Comment by ventoy** [comment]
Compare with other boot tools (e.g. Rufus), Ventoy use different mechanism to boot an ISO file. Ventoy will emulate the ISO file as a CDROM to boot it. That's why sometime that an ISO file can boot OK with other tools to burn to USB but has problem when boot from Ventoy.
Actually, what Ventoy does is much like booting a CD with physical optical drive although physical optical drive is rarely used nowadays.

**So if the ISO file can not boot from CD/DVD then Ventoy can not boot it also.**

Anyway, since Active boot Disk is provided in ISO file format, it should be guaranteed to be able to boot from CD/DVD normally.  It's a matter of course.
