### ISSUE TITLE
[issue]: Compatibility

### ISSUE THREAD

**Issue by JeanSantosReyes** [ventoy/Ventoy#1380]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

Yes.

### What happened?

how can i put ventoy in a false usb, the memory works correctly, it's just not original

**Comment by ventoy** [comment]
What do you mean about a false USB? It has hardware problem?  bad sectors?
What's the problem now if you install Ventoy to it?

What do you mean about " the memory works correctly" ? Can it pass the test of some tools?

**Comment by JeanSantosReyes** [comment]
> What do you mean about a false USB? It has hardware problem? bad sectors? What's the problem now if you install Ventoy to it?
> 
> What do you mean about " the memory works correctly" ? Can it pass the test of some tools?

What I mean by fake memory is that it is not an original memory, I bought it as if it were from kingston but the computer recognizes it as another brand (VendorCo Disk 3.0), but this memory works correctly, that's why I wanted to know if there is any patch to skip that problem, since it gives me problem 6 from FAQ, Ventoy boot in grub shell

**Comment by ventoy** [comment]
`but this memory works correctly`
That may because that you don't save too much data in it. If you save data  in exactly the capacity size (e.g. 32GB) to it then some part of the data may be corrupted.

You can try to reserve some space at the end of the USB when install Ventoy.
For example, we assume that the 1st 8GB of the USB is OK, then you can reserve  24GB space when install Ventoy.
https://www.ventoy.net/en/doc_disk_layout.html#reserve_space

**Comment by ventoy** [comment]
I  close the issue now after 90+ days without response.
If you have any update, please reopen the issue.
