### ISSUE TITLE
[issue]: Easy Recovery Essentials for Windows11

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#1481]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

8gb

### Disk Manufacturer

Virtual Disk (vhd)

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.mediafire.com/file/gdg9f5sg7lz67ct/EasyRE_W11.iso/file

### What happened?

hi @ventoy
Ventoy can not support Easy recovery essentional win11 ISO file..
I captured a video about this ISSUE
Video Link: https://vimeo.com/682340944

Can you add [Easy Recovery Essentials](https://neosmart.net/EasyRE/) for Windows11 ISO support to Ventoy?

program web site : https://neosmart.net/EasyRE/#buy
[https://neosmart.net/blog/2022/free-wind...-download/](https://neosmart.net/blog/2022/free-windows-11-repair-and-recovery-tool-download/)

**Comment by ventoy** [comment]
@crasadure 
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1941026480
https://www.ventoy.net/en/doc_github_ci.html

**Comment by crasadure** [comment]
I tested CI release version..It is OK :) 
Thanks for your support!

**Comment by JackBouchard** [comment]
**I was exploited by CanCap Crypto Exchange and was made to invest $112,000 worth of Canadian dollars into crypto trading by this company. They made it all look real and it was impossible to easily figure out the sham they were running. I was just like every other curious person and investor who decided to invest in cryptocurrency trading but I was exploited and lost my hard-earned money to this scam, if not for the intervention of Morphohack, a cyber security and crypto recovery expert who has been able to help top officials from the government recover their cryptocurrency successful, I would have not been able to recover my crypto assets. CanCap contacted me through a popular figure on Facebook who I later found out to be a sham too, and Morphohack made me realize many other victims like me invested in this platform, I’m bringing this to you here that it was a scam to steal crypto from people. Morphohack was able to recover my crypto successfully and has since been able to assist two of my partners in recovering their crypto from the CanCap crypto investment scam. If you wish to contact Morphohack, you can reach them via the info below: WhatsApp: +1  (213) 672   4092  Or Morphohack@Cyberservices.com**
