### ISSUE TITLE
[issue]: Latest Fedora 36 beta didn't boot in MBR mode

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#1545]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

4 GB

### Disk Manufacturer

Unknow

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/test/36_Beta/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-36_Beta-1.4.iso

### What happened?

Message : did not find /dev/dm-0 . Checksum Ok, works on UEFI machine but not on MBR one.
Key made with Rufus in dd mode works in both MBR and UEFI

**Comment by enigma131** [comment]
Yes was written above, and Fedora has an integrated checksum in second line of grub, tested in uefi mode
Else https://getfedora.org/static/checksums/36_Beta/iso/Fedora-Workstation-36_Beta-1.4-x86_64-CHECKSUM is also ok via m key press and sha256 calc

**Comment by enigma131** [comment]
Any solution for this ?

**Comment by Just4pLeisure** [comment]
I have this issue too with the KDE spin, [Fedora-KDE-Live-x86_64-36_Beta-1.4.iso](https://download.fedoraproject.org/pub/fedora/linux/releases/test/36_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-36_Beta-1.4.iso), but only when VTOY_LINUX_REMOUNT is set to 1 to allow mounting the ISO partition:

> [    8.334510] dracut: FATAL: Failed to mount block device of live image
> [    8.334573] dracut: Refusing to continue
> [    8.332625] dracut-initqueue[1067]: mount: /run/initramfs/live: special device /dev/dm-0 does not exist.
> [    8.332929] dracut-initqueue[1067]:        dmesg(1) may have more information after failed mount system call.
> [    8.988920] reboot: System halted

The live disk starts normally however without VTOY_LINUX_REMOUNT (also when explicitly set to 0 in ventoy.json). 

Behaviour is the same for Legacy BIOS and UEFI using Ventoy version 1.0.73

I am happy to test proposed fixes

**Comment by enigma131** [comment]
Yep, with VTOY_LINUX_REMOUNT set to 0 it works.

**Comment by formlessdao** [comment]
Seems people keep having issues with Both Fedora 35 and 36 and are opening bug reports but Ventoy author seems to not care very much to test it himself and find what is the problem.

**Comment by CodeCubeNeo** [comment]
Fedora is dropping support for leagcy bios, read from their website. It doesnt worke bevause fedora doesnt support it anymore, not because of ventoy

**Comment by ventoy** [comment]
@enigma131 @Just4pLeisure 
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2177016950
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Just4pLeisure** [comment]
@ventoy Thank you for making this CI version available for testing. I have installed it on my USB stick and can confirm that [Fedora-KDE-Live-x86_64-36_Beta-1.4.iso](https://download.fedoraproject.org/pub/fedora/linux/releases/test/36_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-36_Beta-1.4.iso) successfully starts for me using this CI version when VTOY_LINUX_REMOUNT is set to 1 and I can mount and use the ISO partition RW now :+1: 

Thank you longpanda :smile: for your almost obsessional (in the best way :sunglasses:) dedication to Ventoy and for adding great features like the ability to mount the ISO partition. Thank you for finding the time to investigate and address the issues a complex project such as yours inevitably has :confounded:.

@CodeCubeNeo thank you for contributing. I appreciate that you posted with the best of intentions but your advice is, on this occasion, incorrect and unfortunately could have been misleading. Fedora, up to and including F36 beta, supports BIOS and UEFI and although enigma131 raised this issue for legacy BIOS the issue is about Ventoy's VTOY_REMOUNT_LINUX feature and affects BIOS and UEFI equally. It is unrelated to the Fedora Governance Committee's proposal to drop support for legacy BIOS, currently targeted for F37: [Fedora targets F37 for dropping Legacy BIOS](https://fedoraproject.org/wiki/Changes/DeprecateLegacyBIOS).

**Comment by CodeCubeNeo** [comment]
Yep, sorry, my bad. I didn't read through fully, just wanted to mention that it may be a problem that fedora won't support legacy but i see that wasn't the case here. I am really sorry for not being more precise from the begining and thanks for reminding me of that.

**Comment by namogreyangel** [comment]
You may install a VM fedora 34 in vmware workstaion in legacy mode.Make it rebootable with ventoy sh files in their manual  and convert the vmdk into a fixed size vhd and name change .vtoy.Its ok as i tested  with it and upgrade into a newest 37 with legacy bios boot. 
Moreover, i edit the vhd i made and edit the grub.cfg inside of it and make it double bootable uefi with legacy bios boot in ver.37.
And now i enjoy playing fedora on my oldest laptop only supports legacy boot.  ; D
