### ISSUE TITLE
[Feature Request]: add this a collection of icons

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1556]
[icons.zip](https://github.com/ventoy/Ventoy/files/8416124/icons.zip)
Here is a collection of icons, the link above.
Many is adapted from [refind-theme-regular](https://github.com/munlik/refind-theme-regular);
Some is from [brunch](https://github.com/sebanc/brunch);
Little is from unknown.

Add these to the theme of Ventoy.

By the way, the resolution that is 1920×1080 looks not well, perhaps, because the size of words is too thin.

**Comment by ventoy** [comment]
It's a good work.
Those who use custom theme will like it.
But Ventoy theme is a simple default theme and will not add icons for distros.
Some reasons are:
1. We couldn't collect all the icons because there are too many distros.
2. Ventoy need to identify every distro to use the right icon. (Currently ventoy doesn't need to identigy every distro)
