### ISSUE TITLE
Either include a repair option, or at least tell the user why Ventoy won't boot so we can fix it

### ISSUE THREAD

**Issue by RobinJ1995** [ventoy/Ventoy#1626]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

I have a Ventoy USB drive with many ISOs on it, one of them being a Windows ISO to perform Windows boot repairs.
Windows, being... what it is, almost always fails to repair the Windows installation but seemingly also messes with the Ventoy partition(s) so that the next time I try to boot into Ventoy I am told "This is NOT a standard Ventoy device and is not supported".
The specific scenario doesn't matter here, because I'm sure there's other ways to trip up Ventoy and have it refuse to work.

Copying over all of the ISOs is a slow, tedious job, and having to do so every single time Windows messes up will kill my USB drive like nothing else could. Since it's (as far as I can tell) not the partition with the ISOs that's the problem, why do I have to format the entire drive, losing all ISOs? Why isn't there an option to repair a Ventoy installation, or install but detect an existing partition with ISOs?

The update option does not fix whatever issue this is.

At the very least, it'd be nice to include in the error message _why_ Ventoy refuses to boot. It's clearly checking some things and deciding "nope, this isn't gonna work". So why not tell us, the user, so we can fix what's broken instead of having to fully start over?

**Comment by ventoy** [comment]
What do you mean about `The update option does not fix whatever issue this is.` ?
1. The update button is grey and can not click
2. The problem still exist after update

**Comment by RobinJ1995** [comment]
Problem still exists after update

**Comment by steve6375** [comment]
It sounds like Windows repair is changing the boot sector or maybe boot files on the USB drive.
Ventoy and Ventoy utilities will check the contents of the boot sector (and other things like partition start, partition 2 start and end, etc.).

Windows repair may see the USB drive as the 'boot device' and thus try to 'fix' the USB drive.
Easiest thing is to remove the USB drive before trying to repair.
If you are using the command line and typing commands, you need to be careful what commands you type because the USB drive is your boot drive and so you must specify exactly which drive letter you want to repair and not use the default commands.
Can you describe exactly how you 'repair' a system? What commands do you use which corrupts the USB drive.
Also, always use the BIOS Boot Select hotkey to boot to USB (e.g. F8, F10, F11, F12 or whatever your BIOS uses) - do NOT change the BIOS boot order so that it boots from the USB drive by default because then Windows may think the boot drive is the USB drive and so try to 'repair' it.

**Comment by ventoy** [comment]
The new release add some error message.
