### ISSUE TITLE
option to rename iso titles

### ISSUE THREAD

**Issue by xbipin** [ventoy/Ventoy#168]
easy2boot has an option where suppose u place a iso file with name as live_cd_x86.iso you can also place a text file with same name such as live_cd_x86.txt and inside it set a title such as "Recovery Live CD Image" so this appear in menu rather than messed up iso filenames which is easier to recognize as such iso filenames are not allowed to have spaces in them.

would it be possible to have this option or even an option to rename menu titles using ventoy.json file?

**Comment by ahmaddxb** [comment]
Yes this would be a nice feature

**Comment by ventoy** [comment]
Ventoy-1.0.13 add a Menu Alias plugin, that should be what you want.

**Comment by ahmaddxb** [comment]
Thanks

**Comment by ruthan** [comment]
I think that it would make sense to enable it in vanilla version as option in Browse menu, because it make big sense to have possibility to have option to add notes to filenames.. Because other you have to remember what and where you wanted to note.. to do time when you are actually boot in to OS, where   - exFAT / NTFS etc files could be renamed.
  For me does not make sense to create aliases, direct file rename would be better.
