### ISSUE TITLE
[issue]: File ventoy/ventoy.cpio missing in VTOYEFI partition

### ISSUE THREAD

**Issue by rogerwindberg** [ventoy/Ventoy#1694]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.77

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### What happened?

I installed Ventoy on a 124GB flash drive and got the "Access Range Limitation" error, so I used the method of preserving disk space (I put -60GB). In the end, the installation completed successfully and my flash drive now has 64GB available for use. When performing a boot test, I get the following message:

Error message: <File ventoy/ventoy.cpio missing in VTOYEDI partition>

![image](https://user-images.githubusercontent.com/69870624/175423962-a59cef26-c2f9-429c-817a-e20b582389c8.png)

Disk:

![image](https://user-images.githubusercontent.com/69870624/175424929-dc5298dd-4cd3-41e1-abd9-b8d3ceb6253d.png)

I tried to reinstall several times but I couldn't solve it.

**Comment by rogerwindberg** [comment]
Resolved issue by preserving more disk space

**Comment by SadMap** [comment]
i get the same error but on 32gb sandisk usb can you show me how did you fixed it

**Comment by steve6375** [comment]
You  probably have a fake usb drive which does not have 32gb, probably only 4 or 8gb.

**Comment by ibay770** [comment]
> Resolved issue by preserving more disk space

what do you mean, and how did you do that?

**Comment by steve6375** [comment]
Presumably he had a fake USB drive which had reduced memory capacity (lied about its size), so he reserved some space at the end of the drive so the EFI partition was now written to memory that existed rather than non-existent memory.
The Ventoy2Disk utility allows you to reserve space at the end of a drive (usually so you can create more partitions for your own use).

**Comment by ibay770** [comment]
Well I had this issue on a 1tb Sandisk SSD , attempting to boot from an older 2009ish dell so idk what the issue was.

**Comment by steve6375** [comment]
Some BIOSes have a USB limitation in that they cant access sectors beyond 128GB.  Maybe your BIOS is one of them? Do later PCs boot OK?
With Ventoy, the boot files are placed at the end of the drive in the 2nd partition.
You could try reserving most of the space when you make the Ventoy drive using the option provided so that the EFI partition is made within 128GB of the start of the 1TB drive?
