### ISSUE TITLE
[issue]: Cannot boot ~2GB Linux Mint ISO(s) with memdisk mode on a PC with 8GB despite being able to boot Hiren's BootCD PE (~3GB) with memdisk mode on the same PC

### ISSUE THREAD

**Issue by NintendoManiac64** [ventoy/Ventoy#1897]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79, 1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB, 128GB

### Disk Manufacturer

Microcenter (32GB), Samsung 830 2.5" SSD connected via SATA

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

It's just the normal various Linux Mint ISOs, and yes I checked their SHA256 hashes

### What happened?

Despite being able to boot the ~3GB Hiren's BootCD PE in memdisk mode on a PC with 8GB of RAM, I am not able to boot the ~2GB Linux Mint ISO(s) in memdisk mode.

Furthermore, I was able to boot the 1.9GB Linux Mint 19.3 Xfce 32bit ISO in normal mode on a PC with only 2GB of RAM, so I would think that 4x that amount of RAM would be plenty for memdisk mode.

**Comment by ventoy** [comment]
It has been noted here: https://www.ventoy.net/en/doc_memdisk.html
![image](https://user-images.githubusercontent.com/59477474/194189997-2dcd211e-2812-4aec-9141-4cfa73f5482a.png)

For Linux Mint ISOs it need to mount the ISO file after boot. So memdisk mode can not be used to boot it.
For linux, only some small livecd isos can use memdisk mode. They don't need to mount the iso file anymore after boot, because all the things are in the initrd.
