### ISSUE TITLE
[issue]: vtoyefi partition is not listed on file explorer of windows

### ISSUE THREAD

**Issue by liluzg** [ventoy/Ventoy#2331]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.90

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64gb

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

None

### What happened?

I installed ventoy to my newest usb Kingston 64gb and vtoyefi partition is not listed on file explorer of windows
but my old ventoy usb drives vtoyefi partition is listed old ventoy usb drives ventoy version is 1.0.88 new usb drives version is latest 1.0.90
the old ones screenshot
![image](https://user-images.githubusercontent.com/51955520/229365416-db8a58a5-c3b3-4183-b4a8-c52c06e2fed0.png)
the new ones screenshot
![image](https://user-images.githubusercontent.com/51955520/229365493-3b68bc89-0d3a-46e3-b607-54b06a700ec3.png)
![image](https://user-images.githubusercontent.com/51955520/229365507-cfd120df-acef-4780-9235-49bc4f16ed69.png)

**Comment by ventoy** [comment]
It's not Ventoy issue, it's about Windows OS.

For MBR partition style:
In Win7/8/8.1 and earlier versions of Win10, the system will only show the first partition of the USB stick. 
Subsequent partitions are not shown, so the EFI partition must be hidden, and it cannot be shown even if you want to.

But since the new version of Win10, all partitions will be shown by default for the USB stick disk. 
Of course, you can delete the drive letter so that it will no longer be shown on your own computer,
but it will still be shown when you plug it into a new computer. There is no general hiding solution.

Ventoy will automatically delete the drive letter of the EFI partition when install/upgrade, 
so the EFI partition will be hidden in the computer which you install/upgrade Ventoy.
But it will still be shown when plugged into another Win10/Win11 computer.

**Comment by liluzg** [comment]
so in any linux os i can see vtoyefi but im using newest version of windows 11 and i cant assign ant letters on it so thx you for the info im gonna use vtoyefi part in linux oses

very funny fun fact:
im using legacy bios and when im put a ventoy directory and ventoy.json on my 64gb ventoy usb drive its showing a error that says out of range so im changed theme in the vtoyefi partition lol but i dont know which file i can edit to change my language in vtoyefi lol

**Comment by ventoy** [comment]
The VTOYEFI partition is only for Ventoy internal use, so you'd better not to change anything in it.
Delete the ventoy directory and ventoy.json file, don't create it manually, just use VentoyPlugson, it will create necessary directory and file.
https://www.ventoy.net/en/plugin_plugson.html

But firstly, your theme must be compatible to grub or it will cause problem.
