### ISSUE TITLE
1st partition specific size?

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [ventoy/Ventoy#239]
Hey,
I want to use this tool, but it formats my complete USB stick to exFAT (64 GB) and I have only 33MB left. Is it possible to use a custom size for the first partition e.g. 28GB? I can not shrink it, so I can not use the USB stick as a data storage anymore, except for the exFAT partition, which I can not encrypt with e.g. LUKS.
TNT2k

**Comment by aksdb** [comment]
I would second that feature request. Alternatively: allow the setup script to create a second data partition.
In my case I would also like to access that partition from within the live image, which is currently not possible with the main partition (probably due to the way it is passed through).

Anyway: fantastic work. I'm highly impressed of how flawless ventoy works with even completely unknown ISO files :smile:

**Comment by ventoy** [comment]
It's in the development plan of Ventoy-1.0.14 #243

**Comment by TheCataliasTNT2k** [comment]
Thanks, I am waiting to test it :)

**Comment by TheCataliasTNT2k** [comment]
Works. Nice, I like it. Thank you.

**Comment by candrapersada** [comment]
how to install Ventoy for 1nd  and 2nd partition without remove partition 3 on the right

**Comment by ventoy** [comment]
When install Ventoy all the partition tables will be clean. But maybe the data on the partition will be left.
So you can first make a try on a temp USB. Just backup the part table and then install Ventoy with right reserved size and then restore the part table for part 3.

**Comment by candrapersada** [comment]
how to try on a temp USB. Just backup the part table?

**Comment by ventoy** [comment]
I mean you can first try with another USB to avoid data loss in current USB.

**Comment by candrapersada** [comment]
I mean is how to create 1nd and 2nd partition without all the partition tables will be clean.
![VirtualBox_Windows 7 Linux Mint_28_06_2020_04_56_38](https://user-images.githubusercontent.com/36833664/85933668-f5512e00-b903-11ea-95f3-9b103e912d3c.png)
