### ISSUE TITLE
fonts in theme not avaiable

### ISSUE THREAD

**Issue by long-walk** [ventoy/Ventoy#245]
If I use a theme the fonts are not loaded.
Problem is that loadfont is not included for this font in grub.cfg

To fix it I suggest to do this two points:

1) include regexp.mod in the ventoy EFI partition
 grub/i386-pc/regexp.mod

2) change the theme block in  ./INSTALL/grub/grub.cfg
    regexp exclude the file from path and loop through to all *.pf2 files to create a loadfont for every theme font
```
insmod regexp
if [ -n "$vtoy_theme" ]; then
    set theme=$vtoy_theme
    regexp --set=theme_path '^(.*)/.*$' $vtoy_theme
    for x in "$theme_path"/*.pf2; do
        if [ -f "$x" ]; then
            loadfont "$x"
        fi
    done
else
    set theme=$prefix/themes/ventoy/theme.txt
fi
```
I tested this with my one theme and it works for me

Thanks for your great work for this project!

**Comment by ventoy** [comment]
I have add it to the development plan of 1.0.14 #243

**Comment by ventoy** [comment]
Ventoy-1.0.14 released. You can specify customized fonts with theme plugin.

**Comment by long-walk** [comment]
Thanks for the solution works fine!

**Comment by Neocazen** [comment]
Hello. Sorry for asking the question here. There is a problem with the theme plugin in the fonts option. I upload two or three fonts to ventoy.json, but it turns out that it only loads the last font described, in all theme options. Title, menu items and Menu title. And even if you don't direct those fonts to any of these options, that last font font is always loaded into the theme.

{
    "theme": {
        "file": "/ventoy/temas/Biker-Girl-2/theme.txt",
        "fonts": [
        "/ventoy/temas/Biker-Girl-2/fonts/dejavu_32.pf2",
        "/ventoy/temas/Biker-Girl-2/fonts/dejavu_sans_14.pf2"
        ] 
    }
