### ISSUE TITLE
[issue]: Can't install any Linux variants on Asus T100 using Ventoy USB boot

### ISSUE THREAD

**Issue by mholl1983** [ventoy/Ventoy#2763]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.096

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

None

### What happened?

A bug happened!

I've tried to install various versions of Linux on my Asus T100 device using a ventoy USB boot stick:
* LMDE 6 (32 bit and 64 bit)
* Linux Mint 21 (64 bit)
* Manjaro Linux (32 bit)

I can boot into the live environment and do the install, but when I reboot the tablet, it goes straight into BIOS and I have no boot options to select until I add the USB stick again. 

Secure boot is disabled, too.

I was under the impression that Ventoy supported 32 bit UEFI. What am I missing?

**Comment by steve6375** [comment]
If the Ventoy Menu says **Ventoy 1.0.97 IA32**  then you have successfully booted in UEFI32 mode.
If a Linux ISO then boots and you can run the Linux installer then Linux is running in UEFI32 mode.
If the _installation_ fails to UEFI32 boot, then the LINUX INSTALLER is the problem, not Ventoy.
You will find (if you Google) that many people have problems installing Linux on a UEFI32 device including the T100 because the installer software usually assumes it has a UEFI64 BIOS.
There are not many Linux installers that actually work for UEFI32. Most workarounds involve adding the bootia32.efi file after the install has completed.

**Comment by mholl1983** [comment]
Thanks for the helpful reply!  Yes, ventoy boots into the right mode. One thing that confuses me, though, is that some 32 bit flavours of Linux (LMDE and Manjaro) don't seem to work either.

The closest I've been able to do is an install of Debian multiarch, but it doesn't detect Wifi.

**Comment by steve6375** [comment]
Some 32 bit iso don't uefi32 boot because they don't include the bootia32.efi boot file inside the iso.

**Comment by mholl1983** [comment]
Ah, got it. Thanks for the help! I was able to get Zorin OS Lite 64 bit running. Appreciate it!
