### ISSUE TITLE
重裝PVE時卡住在searching for block device containing the ISO proxmox-ve-6.2.1

### ISSUE THREAD

**Issue by hxhwing0522** [ventoy/Ventoy#281]
第一次使用ventoy安裝PVE時(pve.iso放在U盤里), 是正常安裝的。

但是，當我想再重裝時。點擊安裝PVE時，就進入以下畫面，並且卡住不動。
searching for block device containing the ISO proxmox-ve-6.2.1
with ISO ID 'd39f6c1c-92f3011ea-8823-ebf1bb1bc4c6' 

我嘗試過使用軟件再安裝U盤，然而仍然一樣。
最後只好用rufus 刷入pve.iso (選擇DD模式)
再次安裝後 就不再卡在那個畫面 很快就跳過了。

**Comment by MakiseKurisu** [comment]
The issue seems to be resolved with the latest PVE 6.4 iso, as I can get to the installer screen successfully (I already did the install with a normal boot USB since I wasn't sure if this will work). Don't remember my Ventoy version but it is relatively recent as well. Didn't test any other combinations though.
