### ISSUE TITLE
Injection plugin not working on Linux

### ISSUE THREAD

**Issue by kmm2** [ventoy/Ventoy#345]
Here is my setup
```
{
    "persistence": [
        {
            "image": "/ISO/linuxmint-20-xfce-64bit.iso",
            "backend": "/ISO/linuxmint-20-xfce-persist.img"
        }
    ],

    "injection": [
        {
            "image": "/ISO/linuxmint-20-xfce-64bit.iso",
            "archive": "/ISO/ventoy-1.0.16-linux.tar.gz"
        }
    ]
}
```
F5 OK
I do not see Ventoy folder/files anywhere: `find / -name "*ventoy*"`
Is it a conflict with "persistence"?

**Comment by ventoy** [comment]
injection just works with initramfs. 
When you boot linuxmint, there are two phase, in the first phase, the initramfs was extracted and then it will load a big squashfs file with  a whole system directory structure in it and swith root to this.

The injection only take effect at the 1st phase. When you enter  phase2, the original initramfs envrioment was hidden, you can't see them.

So injection is normally for inject drivers. For example, if there is no USB driver for the disk, then in the phase1, it will not be able to access the disk and get the squashfs file, and can't enter phase2.

**Comment by kmm2** [comment]
Thank you for the clarification!

**Comment by ventoy** [comment]
OK, I will close the issue now.

**Comment by NintendoManiac64** [comment]
> So injection is normally used to inject drivers.

Is this still the case? The page for injecting files into live Linux ISO seems to have been created after this issue ([archive link](https://web.archive.org/web/20210928171249/https://www.ventoy.net/en/doc_live_injection.html)), and  the example test archive has a file that ends up being located at `/home/test` which is very much not where drivers would go.

This makes me think Ventoy now has a bespoke method for injecting files into the Linux desktop environment for that "phase2" you mentioned that didn't exist back when this issue was created.
