### ISSUE TITLE
boot fail on lenovo xiaoxin pro13 2020

### ISSUE THREAD

**Issue by WhisperwindBill** [ventoy/Ventoy#42]
i have tried on dell ins 5580 ,it's successfully boot to windows 10 intall.but on lenovo xiaoxin pro 13 2020,it can't boot even if I disabeld secure boot

**Comment by ventoy** [comment]
It may be due to Ventoy's secure boot solution. Since 1.0.07 Ventoy add support to secure boot, but the solution is not perfect enough, it will not work on some mathine no matter secure boot is enabled/disabled.
Linpus lite boot failed is the most common cases of them.
So in the next release, I will add an option during installation for secure boot, for these machines user can uncheck secure boot support. Then disabled secure boot in BIOS and use Ventoy.

For 1.0.08, if you want to try, you can do as follows:
Find a way to mount the second partition of Ventoy (EFI FAT partition), there will be 4 files, in \EFI\BOOT directory: BOOTX64.EFI grubx64.efi grubx64_real.efi MokManager.efi
Just rename BOOTX64.EFI to another name like abc.efi and rename grubx64_real.efi to BOOTX64.EFI

Then Ventoy may work with UEFI when you disable secure boot in BIOS.

**Comment by WhisperwindBill** [comment]
yes! my laptop show Linpus lite boot failed when i try to boot with usb disk,thks
