### ISSUE TITLE
1.0.21 MBR boot - F5 - Resolution Configuration gives blank screen

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#475]
![image](https://user-images.githubusercontent.com/1469350/93067216-d9436a00-f672-11ea-8256-031488958621.png)

![image](https://user-images.githubusercontent.com/1469350/93067180-ca5cb780-f672-11ea-8b53-7280a5c6524c.png)

Virtual Box v5 - MBR boot.

**Comment by ventoy** [comment]
In the boot menu, please press `c` to enter shell, and run  `videoinfo`  to see the output.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/93071568-31309f80-f678-11ea-997c-8082c8c1f93c.png)

**Comment by ventoy** [comment]
Please give a Virtual Box download link for this version, I will download and test it.

**Comment by crasadure** [comment]
hi steve6375;
serhat100 from TNCTR sent a message for you..this is the message:

![1](https://user-images.githubusercontent.com/54566818/93107996-f865ea00-f6ba-11ea-95af-b96187c8ba89.jpg)

When 1440x900x32 is selected, the image in the picture below is formed
![2](https://user-images.githubusercontent.com/54566818/93108079-103d6e00-f6bb-11ea-933c-99d77e6d2e9a.jpg)

I made an addition in ventoy grub.cfg.

850. if [ "$grub_platform" = "pc" ]; then
if vt_check_mode 0; then
legacy_iso_memdisk $vtoy_iso_part $vt_chosen_path
else
legacy_iso_menu_func $vtoy_iso_part $vt_chosen_path
fi
else
if vt_check_mode 0; then
uefi_iso_memdisk $vtoy_iso_part $vt_chosen_path
else
uefi_iso_menu_func $vtoy_iso_part $vt_chosen_path
fi
fi
set gfxmode=1920x1080,1366x768,1024x768,800x600,auto ### (I added it, I tested it 4 times because it works, I didn't encounter any problems. But I don't know if it's a coincidence)
terminal_output gfxterm
boot
}

seems to solve the problem but I'm not sure.

**Comment by steve6375** [comment]
Closing - it was an issue with badly copied files. It also failed on real system, so I compared files and found error.
