### ISSUE TITLE
mAid (m)anage(A)ndro(id) iso fails to boot

### ISSUE THREAD

**Issue by AleD219** [ventoy/Ventoy#477]
`:: running hook [archiso]`
`:: running hook Earchiso_loopmnt] `
`:: Mounting l/deu/disk/by-label/mAid_nightlys to s/run'archiso/bootmnt'`
`Waiting 30 seconds for device /dev/disk/by-label/mAid_nightly ...`
`ERROR: '/dev/disk/by-label/mAid_nightly' device did not show up after 30 seconds...`
`Falling back to interactive prompt`
`You can try to fix the problem manually, log out when you are finished`
`sh: can't access tty; job control turned off`
`[rootfs ]#`

mAid iso (https://leech.binbash.rocks:8008/mAid/mAid_v2020-09-15_11-40_x86_64_forgetful.iso) fails to boot. it is based on manjaro, and uses refind bootloader

**Comment by ventoy** [comment]
I have supported it and will be avaliable in the next release.

**Comment by ventoy** [comment]
Please test with 1.0.22

**Comment by AleD219** [comment]
Works fine now, thanks a lot

**Comment by steadfasterX** [comment]
haven't recognized that mAid is supported by ventoy! nice! :) 

could you pls re-check @ventoy ? unfortunately it does not work anymore (likely due to changes in mAid over the last 3 years).

I would suggest testing always with the latest _stable_ ones (atm of writing v4.1):

- latest stable **_full_** release: https://sourceforge.net/projects/maid-linux/files/v4/mAid_v4.1-full_x86_64.iso/download
- latest stable **_light_** release: https://sourceforge.net/projects/maid-linux/files/v4/mAid_v4.1-light_x86_64.iso/download

Current releases can be found here always: https://sourceforge.net/projects/maid-linux/files/
