### ISSUE TITLE
[BUG]联想小新潮7000，8代U，无法引导。

### ISSUE THREAD

**Issue by EX-XD** [ventoy/Ventoy#525]
做U盘时两种模式都试了，不管勾不勾选支持安全启动，都无法正常引导，直接提示失败，回车后自动重启。
试了3个U盘，皆不行。
WePE写的盘可以正常引导。不过WePE写的盘应该是多种模式，但是直接进入的UEFI引导。

**Comment by ventoy** [comment]
试一下，
不勾选支持安全启动，同时BIOS里面把安全启动关闭。注意要两个条件同时满足。

**Comment by EX-XD** [comment]
关安全启动支持＋关安全启动可以引导，再开启安全启动后又不能引导，勾选支持也不行

**Comment by EX-XD** [comment]
测试版本号为1.0.22，最新的23/24都未测试

**Comment by EX-XD** [comment]
1.0.24测试完，依然报错，BIOS安全启动开启+支持安全启动勾选，Linpus lite boot failed.

**Comment by ventoy** [comment]
对于有 Linpus lite 错误的情况，当前必须同时满足
不勾选支持安全启动，同时BIOS里面把安全启动关闭。 这两条缺一不可。
在 https://www.ventoy.net/cn/doc_secure.html  有说明

**Comment by EX-XD** [comment]
就是说目前ventoy没法完美支持开了安全启动的电脑对吧？实现原理问题么？直接的PE似乎很少遇到这种问题

**Comment by ventoy** [comment]
是的，有些机器上有问题。PE是Windows的范畴，安全启动就是微软主导的，所以直接启动winpe天生没问题。但是ventoy是先启动grub再启动其他的，安全启动开启的情况下能启动grub这一步也是不容易的，毕竟不是微软亲生的。



    


            在2020年10月26日 22:17，EX-XD 写道： 

就是说目前ventoy没法完美支持开了安全启动的电脑对吧？实现原理问题么？直接的PE似乎很少遇到这种问题



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ventoy/Ventoy/issues/525#issuecomment-716575924",

"url": "https://github.com/ventoy/Ventoy/issues/525#issuecomment-716575924",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
