### ISSUE TITLE
I am sorry :(

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#587]
My ventoy usb has 2 partition. One where I store iso files and another where I store my bash scripts and other files. I just noticed that I am not able to update it although I am not using any other bootloader. Please help. I am sorry for all the trouble which I gave you regarding mac support. I will never comment on it anymore.

Please tell me how can I update ventoy usb and also having my folders. Those folders cannot be with iso files because it cannot be accessed with ventoy togeather. Or please add an option to store files. Currently there is no point in having to reserve space on usb because then ventoy cannot be updated.

**Comment by skulldealer** [comment]
Why are you ignoring me? I am leaving ventoy now.

**Comment by blackcrack** [comment]
8-|  holymoly.. what a ....
He want go in psycho.. okey.., this is not fine, but okey...
he don't know how it works ..
good to be closed ..

**Comment by julianpoemp** [comment]
@skulldealer I think you don't understand how issues on Github work: Developers of open source projects do their work often in their free time and offer their products for free. So you you can't expect responses to your issues in less than 24 hours. In most cases you will wait much longer (weeks, months). As I said in other discussions this is not a chat: Post one issue to only one topic and summarize your issue as much as possible. Github users don't like to read 10 comments in a row by the same author and don't want to get 10 emails because of it. All these points were already explained to you, but you have ignored it oviously. Perhaps you will understand this in the future and you will change your behaviour on other Github repositories
