### ISSUE TITLE
Kali Linux : stuck on screen glitch

### ISSUE THREAD

**Issue by KaKi87** [ventoy/Ventoy#650]
Hello,

Wether I'm using the latest `kali-linux-2020.4-live-amd64.iso` or the recommended `kali-linux-2020.1b-live-amd64.iso`, I'm getting the following screen after selecting it :

![IMG_20201215_172555](https://user-images.githubusercontent.com/21284089/102243289-488f5b00-3efb-11eb-9373-6f920f990cf3.jpg)

On a 64-bit laptop.

Thanks

**Comment by ventoy** [comment]
When you boot into Ventoy's menu, press `F5--->Screen Display Mode`   and select `Force Text Mode`  then press ESC to return and select the ISO file to boot.

**Comment by KaKi87** [comment]
I swear it didn't worked the first time, but it worked every next time.

Thanks !

Since I'm also experiencing this issue with other ISOs, do you think it would be possible to add an optional feature in Ventoy2Disk allowing to set display mode to text by default at boot ?

Thanks !

**Comment by ventoy** [comment]
There is a theme plugin, you can set text mode as the default boot mode.
https://www.ventoy.net/en/plugin_theme.html

Just set this in ventoy.json
```
{
    "theme": {
        "display_mode": "CLI"        
    }
}
```

**Comment by KaKi87** [comment]
Should I remove the other keys (`file`, `ventoy_left`, `ventoy_top`, `ventoy_color`) ?
Will I have to use `Install` or will I be able to use `Update` ?
Thanks !

**Comment by ventoy** [comment]
No, don't use the example on the website, just use the simple content i write in the reply.You don't need to install or update, just put the ventoy.json file in ventoy directory and that's all On 12/16/2020 23:17, KaKi87 wrote: 
Should I remove the other keys (file, ventoy_left, ventoy_top, ventoy_color) ?
Will I have to use Install or will I be able to use Update ?
Thanks !

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/650#issuecomment-746457149",
"url": "https://github.com/ventoy/Ventoy/issues/650#issuecomment-746457149",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by KaKi87** [comment]
> No, don't use the example on the website, just use the simple content i write in the reply.

Yes I was talking about your example.
I was talking about the fact that in the current `ventoy.json` file, I see this :
```json
    "theme": {
        "file": "/ventoy/theme/theme.txt",        
        "display_mode": "GUI",
        "ventoy_left": "5%",
        "ventoy_top": "95%",
        "ventoy_color": "#0000ff"
    }
```
And I was wondering if I should only keep the `display_mode` key with the `CLI` value or also keep the others unchanged.

> You don't need to install or update, just put the ventoy.json file in ventoy directory and that's all

Do you mean on the USB key ? There is no `ventoy` folder on it, should I create it ?
Or do you want me to mount the `VTOYEFI` partition ? If so, how do I do that on Windows ?

Thanks !

**Comment by ventoy** [comment]
yes, only display_mode is needed.You need to create a directory with name ventoy On 12/16/2020 23:37, KaKi87 wrote: 

No, don't use the example on the website, just use the simple content i write in the reply.

Yes I was talking about your example.
I was talking about the fact that in the current ventoy.json file, I see this :
    "theme": {
        "file": "/ventoy/theme/theme.txt",         
        "display_mode": "GUI",
        "ventoy_left": "5%",
        "ventoy_top": "95%",
        "ventoy_color": "#0000ff"
    }
And I was wondering if I should only keep the display_mode key with the CLI value or also keep the others unchanged.

You don't need to install or update, just put the ventoy.json file in ventoy directory and that's all

Do you mean on the USB key ? There is no ventoy folder on it, should I create it ?
Or do you want me to mount the VTOYEFI partition ? If so, how do I do that on Windows ?
Thanks !

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/650#issuecomment-746490664",
"url": "https://github.com/ventoy/Ventoy/issues/650#issuecomment-746490664",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by KaKi87** [comment]
Creating a `ventoy/ventoy.json` file from the root of the ISOs location work, thanks !
