### ISSUE TITLE
Windows auto install not working

### ISSUE THREAD

**Issue by sraedler** [ventoy/Ventoy#663]
# The Structure

- ventoy (folder)
  - ventoy.json
  - script (folder)
    - autounattend.xml
- ISO (folder)
  - Windows10_20H2.iso
-  unattended_files (folder)
  - Windows10_20H2_privat.zip (containing a folder structure and files)

[ventoy.json](https://github.com/ventoy/Ventoy/files/5729224/ventoy.log)
[autounattend.xml](https://github.com/ventoy/Ventoy/files/5729236/autounattend.log)

The ventoy.json is attached as ventoy.log

I don't know why this is not working. The unattended setup is not executed.
The Windows10_20H2.iso is downloaded with the current Rufus version (German ISO file).
The autounattended.xml is also uploaded as autounattended.log. It should just skip all steps except the WIFI setup. The key is just a dummy found on the internet.

However, once I had a hint that the EULA is missing. Nevertheless, I can not fix this issue.

Could you please help me out?

**Comment by ventoy** [comment]
```
{
    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" }
    ],
    
    "auto_install" : [
        {
            "image": "/ISO/Windows10_20H2.iso",
            "template": "**/unattended/autounattend.xml**"
        }
    ],
    
    "injection": [
            {
            "image": "/ISO/Windows10_20H2.iso",
            "archive": "/unattended_files/Windows10_20H2_privat.zip"
        }
    ]
}
```

Should "template": "**/unattended/autounattend.xml**"  be  "template": "**/ventoy/script/autounattend.xml**"  ?

**Comment by sraedler** [comment]
Yes, sure!

I just uploaded the wrong version. The correct one here: [ventoy.xml](https://github.com/ventoy/Ventoy/files/5729473/ventoy.log)


Additionally, the ventoy tool is not telling any issues. 

If I start the unattended setup, the xml is not executed and the following results occurs:
First,: "An unexpected error occurs. Please restart the setup" (roughly translated)
Second: ![image](https://techcommunity.microsoft.com/t5/image/serverpage/image-id/29165i12D566ACDAC5D461/image-size/large?v=1.0&px=999)

**Comment by ventoy** [comment]
Please Press F5 to check the configuration.Did it prompt you to select boot with or without autoinstalltion? On 12/22/2020 19:15, sraedler wrote: 
Yes, sure!
I just uploaded the wrong version. The correct one here: ventoy.xml
Additionally, the ventoy tool is not telling any issues.
If I start the unattended setup, the xml is not executed and the following results occurs:
First,: "An unexpected error occurs. Please restart the setup" (roughly translated)
Second: 

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/663#issuecomment-749489197",
"url": "https://github.com/ventoy/Ventoy/issues/663#issuecomment-749489197",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ventoy** [comment]
If you don't set the autoinstall configuration, does it setup successfully?

**Comment by sraedler** [comment]
>Did it prompt you to select boot with or without autoinstalltion?
yes, it prompts. I select autoinstall.

>If you don't set the autoinstall configuration, does it setup successfully?
Yes, I can install it if I click start without autoinstall

**Comment by DX37** [comment]
> Can you propose a xml that you used for testing? I just want to skip all steps

I can give yoy successfully tested unattended file - [skip_oobe.txt](https://github.com/ventoy/Ventoy/files/5741271/skip_oobe.txt). Please rename it's extension to xml and try it.

**Comment by sraedler** [comment]
@DX37 thanks for the suggestion and sorry for my late reply!

Unfortunately it does not work. The xml is executed as well as it is with my xml file. However, the file does not work with the windows version.

**Comment by steve6375** [comment]
The error message can be caused by the wrong Product Key being used in the XML file.
It can also be caused by lack of memory RAM in the system. I think Ventoy requires more RAM than a normal flat-file boot.

**Comment by ventoy** [comment]
> The error message can be caused by the wrong Product Key being used in the XML file.
> It can also be caused by lack of memory RAM in the system. I think Ventoy requires more RAM than a normal flat-file boot.

Not exactly. 
Ventoy just requires little additional RAM when booting Windows (1~2MB).

**Comment by sraedler** [comment]
I was able to make this work after hours and plenty of tests.
However, I have no idea about the problem and how I solved it.

Thanks for your help!
