### ISSUE TITLE
Parrot OS 4.11 installer can't mount installation media

### ISSUE THREAD

**Issue by librenix** [ventoy/Ventoy#704]
Parrot OS 4.11 installer can't mount /dev/sdb2 to /cdrom: no such device, LiveCD works, but 4.10 works fine. 

BTW: I tested void-live-x86_64-musl-20201224-mate.iso in UEFI mode and it worked fine.

**Comment by ventoy** [comment]
Where to download the iso file?

**Comment by librenix** [comment]
@ventoy https://mirrors.dotsrc.org/parrot/iso/4.11-beta2/
See also:
https://community.parrotsec.org/t/parrot-xfce-4-11-beta-testing/17364/6

**Comment by ventoy** [comment]
I think it's a problem of the iso file itself.
If you connect the iso file directly to a VirtualMachine(e.g. VMware/VirtualBox) it can not boot fine too.
I find that it miss a `isofs.ko` driver in `/install/initrd.gz`  and it exist in `/live/initrd.img` so that's why it's ok with LiveCD boot option but failed with Install option.
I think you can report an issue to the parrot community.

**Comment by librenix** [comment]
@ventoy I see, thank you.
