### ISSUE TITLE
TROM-jaro 20.01.2021 not work

### ISSUE THREAD

**Issue by Scoty43** [ventoy/Ventoy#712]
On the website fromTROM-jaro i read i can use it with Ventoy but not work Whene i boot this Image i get th error no uefi.x64 found.

**Comment by ventoy** [comment]
I just test `TROM-Jaro 20.01.2021.iso` in VirtualMachine  and my laptop with Ventoy and it boot fine in both legacy BIOS mode and UEFI mode.

**Comment by Scoty43** [comment]
I have upload a screenshot from the error.
https://www.directupload.net/file/d/6074/lomv7775_jpg.htm

**Comment by ventoy** [comment]
Can you boot other ISO files fine in the same environment (e.g.  Ubuntu) ?

**Comment by Scoty43** [comment]
Yes other working.

**Comment by ventoy** [comment]
When you in Ventoy's boot menu, press `c` to enter grub shell and run `vtdebug on` and then press ESC and select the ISO to boot.
This time there will be many debug messages. You can give a video or some photos about it.

**Comment by Scoty43** [comment]
I have make a Video. I hope you can see what you need.

https://streamable.com/unksbq
or
https://drive.google.com/file/d/1_iFiQWVlXJ3r4Nui4mUaaOp7JfWOjA6-/view?usp=sharing

**Comment by ventoy** [comment]
My `TROM-Jaro 20.01.2021.iso` is  `2787127296` size in byte. But in your video it's `2666004741`, is the file corrupted?

**Comment by Scoty43** [comment]
I have download 2x but the same.

**Comment by ventoy** [comment]
Is the iso file you download 2666004741 bytes? On 01/26/2021 23:26, Scoty43 wrote: 
I have download 2x but the same.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/712#issuecomment-767618986",
"url": "https://github.com/ventoy/Ventoy/issues/712#issuecomment-767618986",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Scoty43** [comment]
I have download now from a other Server and test tomorrow again.

**Comment by ventoy** [comment]
OK. 2666004741  is definitely invalid size for an iso file.Because the size for an iso file must be multiple of 2048. On 01/26/2021 23:44, Scoty43 wrote: 
I have download now from a other Server and test tomorrow again.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/712#issuecomment-767631210",
"url": "https://github.com/ventoy/Ventoy/issues/712#issuecomment-767631210",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Scoty43** [comment]
Yes you are right. The ISO from other hoster working. The ISO direct from TROM-jaro are corrupt.
