### ISSUE TITLE
Windows 10 Installer giving boot error 0xc000014c with Ventoy 1.0.33

### ISSUE THREAD

**Issue by ryu-ketsueki** [ventoy/Ventoy#722]
I recently formatted a 32 GB Sandisk Ultra Dual Drive with Ventoy and placed the following ISOs in there:

- Feren OS
- Hirens Boot CD PE
- openSUSE Krypton
- openSUSE Leap 15.2 DVD
- openSUSE Tumbleweed NET
- Pop OS 20.04 Intel/AMD
- Pop OS 20.04 NVIDIA
- Regata OS 20
- Ubuntu 20.04.1
- Windows 10 x64
- Windows 7 All Versions

I use those ISOs on my work whenever I need to do maintenance on machines and the rare occasions I have to reinstall the operating system, so it's why I have both Windows 7 and 10 Installers. However, those are the only ones that don't boot at all, while all the others, including Hirens Boot CD PE, boots just fine. This happens in both Legacy and UEFI and I'm sure it's not ISO fault because I use those ISOs for a while now, I used them with a Legacy setup using YUMI before switching to Ventoy, so they are not corrupt, and they also boot just fine on a virtual machine as well.

My focus for now is the Windows 10 Installer. I downloaded this ISO from Microsoft's website, so it is up to date. While it doesn't boot at all through Legacy, it shows the boot error 0xc000014c if booting through UEFI.

My test machine is a Lenovo ideapad 330-15IKB. It has Legacy support enabled, no Secure Boot.

**Comment by ventoy** [comment]
Please do a test.Press Ctrl+i in ventoy boot menu, then select the iso file to boot.  On 01/27/2021 23:08, Ryū Ketsueki wrote: 
I recently formatted a 32 GB Sandisk Ultra Dual Drive with Ventoy and placed the following ISOs in there:

Feren OS
Hirens Boot CD PE
openSUSE Krypton
openSUSE Leap 15.2 DVD
openSUSE Tumbleweed NET
Pop OS 20.04 Intel/AMD
Pop OS 20.04 NVIDIA
Regata OS 20
Ubuntu 20.04.1
Windows 10 x64
Windows 7 All Versions

I use those ISOs on my work whenever I need to do maintenance on machines and the rare occasions I have to reinstall the operating system, so it's why I have both Windows 7 and 10 Installers. However, those are the only ones that don't boot at all, while all the others, including Hirens Boot CD PE, boots just fine. This happens in both Legacy and UEFI and I'm sure it's not ISO fault because I use those ISOs for a while now, I used them with a Legacy setup using YUMI before switching to Ventoy, so they are not corrupt, and they also boot just fine on a virtual machine as well.
My focus for now is the Windows 10 Installer. I downloaded this ISO from Microsoft's website, so it is up to date. While it doesn't boot at all through Legacy, it shows the boot error 0xc000014c if booting through UEFI.
My test machine is a Lenovo ideapad 330-15IKB. It has Legacy support enabled, no Secure Boot.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/722",
"url": "https://github.com/ventoy/Ventoy/issues/722",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ryu-ketsueki** [comment]
Same error code in compatibility mode.

**Comment by ryu-ketsueki** [comment]
I ended using YUMI UEFI for what I needed but the error still persists on Ventoy

**Comment by steve6375** [comment]
When using my IdeaPad 300, I find that the left-hand USB3 port gives issues such as 0xc0000178 with some WinPE ISOs.
Also the left-hand port only seems to detect USB drives on power-on - a warm reboot often does not list the USB drive.
Did you try booting using the right-hand USB 2 port on the IdeaPad?

**Comment by ryu-ketsueki** [comment]
There are no right hand ports in this model of the ideapad. The USB ports are all on the left hand side. Two USB-A and one USB-C. I didn't notice a difference between them so I think all of them are USB 3

**Comment by steve6375** [comment]
OK - well try each USB port.
Turn off IdeaPad - turn on IdeaPad - test - Turn off IdeaPad
Repeat for all three USB ports.
Then try again but use a USB 2 extension cable.

**Comment by ryu-ketsueki** [comment]
> OK - well try each USB port. USB 3 ports are usually blue.
> Turn off IdeaPad - turn on IdeaPad - test - Turn off IdeaPad
> Repeat for all three USB ports.
> Then try again but use a USB 2 extension cable.

Sorry for the delay. I tested all ports. All the three are USB 3.

**Comment by steve6375** [comment]
And what if you connect them via a usb 2 cable?

**Comment by ryu-ketsueki** [comment]
I don't have that at my disposal and it doesn't make sense that select modern windows ISOs need to work through an outdated USB connection

**Comment by madhavpcm** [comment]
Im getting the same issue for win10_x64_english_20H2. However in Qemu there is no issue and the iso works fine. But I have tried to boot to windows from like 3 machines, all machines give the same error code 0xc000014c, USB 2 or USB 3 regardless.

**Comment by steve6375** [comment]
Do you mean UEFI64-booting from a Ventoy USB drive using QEMU works OK?
What '3 machines' did you test with?

**Comment by madhavpcm** [comment]
I'm not sure if it was UEFI booting, this was my trigger ```sudo qemu-system-x86_64 -hdb /dev/sda -m 2G```. Ventoy opens up, I chose the windows ISO and it loads OK. 
3 Machines were 2 laptops and a desktop(all UEFI), all machines come to Ventoy from boot menu, then when I chose windows I get this error in all 3 machines. I tried another linux ISO and it doesnt have any issues.

**Comment by steve6375** [comment]
Ventoy tells you what mode it is in - look near the bottom of the menu.

**Comment by madhavpcm** [comment]
Qemu was booting in BIOS(no issues with installer), however I managed to  run it with UEFI. However this time , on choosing windows in UEFI, I get a black screen for a couple of seconds and the machine restarts.

**Comment by cppcooper** [comment]
Same issue I had. I only have the windows 10 iso, and I tried ventoy only because everything I had tried resulted in the windows installer claiming it was missing media drivers that it needed and I couldn't progress through the setup. Pretty sure I don't have a single usb 2 port. But also, diskpart saw the usb disk and its partition it did not see a volume associated however. That's all the info I've got to contribute, I'm not terribly invested in installing windows so not gonna troubleshoot further.

**Comment by rambip** [comment]
I have the exact same issue.
I get an error saying that the "BTC" is not present, so this is related to DVD installers ?

I accidentally deleted the "/EFI/Boot" partition of my machine while installing linux, and I can't start the windows installer (most recent iso) with ventoy.

I can boot every linux distro, it seems that the most recent windows iso doesn't work well with ventoy ...

A fix would be nice !

**Comment by ryu-ketsueki** [comment]
Okay so here's what I did. I have an USB-C to USB-A adapter that happen to work only on USB 2 so I could test the USB stick with Ventoy like that. The problem is still the same on USB 2.

I gave up on trying to flash Windows 10 Installer on an USB stick and the workarounds people suggested me about just copying the content of the image to the USB stick formatted as NTFS doesn't work in my case. Rufus also didn't work for some reason and YUMI doesn't copy the contents to the stick. I'm left with no other way of putting the installer on a stick. In the end, I found a workaround that allowed me to install Windows on the computer by using a VM but that is way too risky and I don't recommend.

And yeah, it would seem the problem is on how Ventoy is reading the image because to not find the BCD file inside an unmodified image is way too weird

**Comment by steve6375** [comment]
Did you check the CRC32 value of the ISO file **on the USB drive** and compare it with the CRC32 value of the same downloaded ISO file that is on your Hard Drive to check that the file on the USB drive is not corrupt?
Are you sure it says 'BTC' not present  and not 'BCD' not present? If it says BTC then you may have a corrupt ISO/bad USB memory.
Try re-formatting the Ventoy first partition as NTFS instead of exFAT.
Can you suggest a URL where the same ISO can be downloaded for testing by us?

**Comment by ryu-ketsueki** [comment]
> Did you check the CRC32 value of the ISO file **on the USB drive** and compare it with the CRC32 value of the same downloaded ISO file that is on your Hard Drive to check that the file on the USB drive is not corrupt?
> Are you sure it says 'BTC' not present and not 'BCD' not present? If it says BTC then you may have a corrupt ISO/bad USB memory.
> Try re-formatting the Ventoy first partition as NTFS instead of exFAT.
> Can you suggest a URL where the same ISO can be downloaded for testing by us?

I'm pretty sure it said BCD. Then I used the same ISO in the VM to do that workaround I said earlier so the problem is not the ISO.
![IMG_20210704_000053](https://user-images.githubusercontent.com/39316730/132379544-256ec567-9822-43d4-b7ef-013dcb7ebecd.jpg)

**Comment by steve6375** [comment]
QEMU should not fail. If you have Windows you could try installing VirtualBox and VMUB and then directly boot from the Ventoy USB drive using the Virtual Box VM (or test with 'QEMUBootTester.exe'. Since many thousands of people use Ventoy and they are not all screaming that it won't boot Windows ISOs, you need to look more closely at your target system, ISO or USB drive.
Just because the ISO file is OK on your hard drive, does not mean it has been copied correctly to your USB drive. You need to check the CRC32 of both ISO files and compare them.
https://youtu.be/mvYkujvUXhc

**Comment by cppcooper** [comment]
I thought that's precisely what this thread/issue is all about.. complaining that it doesn't boot windows ISOs. Your logic seems highly suspect.

**Comment by madhavpcm** [comment]
I did verify md5-checksum but it was a few months ago. To be clear,It did NOT boot in my desktop and 2 laptops of different eras. Qemu gave same 0x0000014c error on UEFI. But on LEGACY It was able to boot and install correctly. By following the discussion above, it only seems to persist on Win10-20H1 isos available from microsoft.com. So it could either be Ventoy not able to do something correctly with that particular ISO or its Microsofts fault.

**Comment by steve6375** [comment]
@madhavpcm. You said 'Im getting the same issue for win10_x64_english_20H2. '  Now you are saying it only happens on 20H1 ??? So they both show the issue in UEFI?
So if you download a current English x64 Win10 ISO from Microsoft now, does that ISO work?
Did you try re-formatting the first partition of the Ventoy drive as NTFS?
Can you supply a download URL of an ISO that shows the issue so it can be downloaded by others to test?

**Comment by madhavpcm** [comment]
My mistake it was 20h2 itself

**Comment by cppcooper** [comment]
I might be mistaken, but I recall trying to change the fs type and ventoy simply not working. Wish I had of made notes now

**Comment by Werew1942** [comment]
> > Did you check the CRC32 value of the ISO file **on the USB drive** and compare it with the CRC32 value of the same downloaded ISO file that is on your Hard Drive to check that the file on the USB drive is not corrupt?
> > Are you sure it says 'BTC' not present and not 'BCD' not present? If it says BTC then you may have a corrupt ISO/bad USB memory.
> > Try re-formatting the Ventoy first partition as NTFS instead of exFAT.
> > Can you suggest a URL where the same ISO can be downloaded for testing by us?
> 
> I'm pretty sure it said BCD. Then I used the same ISO in the VM to do that workaround I said earlier so the problem is not the ISO. ![IMG_20210704_000053](https://user-images.githubusercontent.com/39316730/132379544-256ec567-9822-43d4-b7ef-013dcb7ebecd.jpg) This happens whenever I try to boot the installer through Ventoy. I checked, double checked, tried a different ISO download, the USB drive is brand new, even boots Hirens BootCD PE without any problems which is also based on Windows 10.

I got this same exact error msg because my Windows iso got corrupted while copying. I checked the sha1sum and it was wrong. Deleted and copied again, checked the crc32 and tried again and it worked. Tested with my HP laptop:

File name: `19043.928.210409-1212.21h1_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso`
Type: `GPT`
Boot: `UEFI`
Ventoy version: `1.0.61`
Laptop: `HP Intel i5`
Download: https://www.microsoft.com/en-in/evalcenter/evaluate-windows-10-enterprise (Free 90days, u can enter dummy data)

**Comment by 4oo4** [comment]
I found the same thing as @Werew1942, the sha256 of the copied ISO didn't match the original. After fixing that I still couldn't get past this error. For some reason, [WoeUSB](https://github.com/woeusb/woeusb) was the only thing I found that could create a successfully bootable thumbdrive from Linux. Not sure if it's a hardware specific thing or not. My suspicion is that the Dell UEFI firmware only will boot from NTFS or FAT32, and only WoeUSB was able to split the .wim files to fit on a FAT32 partition.

File name: Win10_21H2_English_x64.iso
Type: GPT
Boot: UEFI
Ventoy Verision: 1.0.43
Hardware: Dell Optiplex 7050 Micro

**Comment by Werew1942** [comment]
Turns out Its a linux problem. Every noticed how fast linux copies the file to the usb? Both cp and by using a gui. Thats because its not actually copied. Run the `sync` command after copying the usb then wait till it completes fully. After that ventoy working flawlessly.

@4oo4

**Comment by ryu-ketsueki** [comment]
> Turns out Its a linux problem. Every noticed how fast linux copies the file to the usb? Both cp and by using a gui. Thats because its not actually copied. Run the `sync` command after copying the usb then wait till it completes fully. After that ventoy working flawlessly.
> 
> @4oo4

I just tested running sync and also made a sha256sum test after it and now the file on the thumbdrive is exactly the same I downloaded. The installer boots just fine on UEFI. I guess that's the end of that issue. Except, this should be made clear somewhere, either when Ventoy is being installed on the drive or on the README file. When that happens, I will close this issue

**Comment by ventoy** [comment]
I have made it an option in the new issue template to remind the file checksum.
![image](https://user-images.githubusercontent.com/59477474/152686326-32bab1f7-51b1-4827-a915-fef7cc2e79ae.png)

**Comment by ryu-ketsueki** [comment]
> I have made it an option in the new issue template to remind the file checksum. ![image](https://user-images.githubusercontent.com/59477474/152686326-32bab1f7-51b1-4827-a915-fef7cc2e79ae.png)

I mean about the sync command. It could be an useful hint. I had no idea about this problem with the cp command.

**Comment by ventoy** [comment]
Have noted here: https://www.ventoy.net/en/doc_checksum.html

**Comment by alator21** [comment]
Had the same problem as OP. It probably was due to a corrupted ISO.
Steps that I followed to fix it(I use ubuntu 22.04):
1. Download the original Windows 11 ISO from microsoft(https://www.microsoft.com/en-us/software-download/windows11)
2. cd into the usb(`cd /dev/sdb1`)
3. cp windows 11 iso to usb(`cp ~/Downloads/W11.iso .`)
4. `sudo sync -f /dev/sdb1`
5. Safely eject the usb drive

The number 4 of the list was crucial as I was pulling the usb drive earlier than I was supposed to.
As an extra tip, you should also calculate and compare the md5 checksum of the ISO after you copy it to the usb and when you use ventoy as well.

`md5sum ~/Downloads/W11.iso >> /dev/sdb1/W11.iso.md5`

**Comment by CarterSnich** [comment]
- used `rsync`
- verified checksum
- updated to latest v1.0.94
- turned off Secure Boot on BIOS and Options in Ventoy
- compatibility mode
- wimboot
- compatibility mode and wimboot


Still getting the 00014c error. Partitioned in GPT.

**Comment by tigitz** [comment]
Facing the same "suspicously fast .iso copy to my usb on ubuntu" issue as noted by @navaneeth-dev and solutioned by @alator21, you can approximatively monitor the `sync` progress by running:

`watch -n 1 grep -e Dirty: -e Writeback: /proc/meminfo` 

The "Dirty" memory includes all data in the system's memory that has been modified but has not yet been written to the disk. But be aware that his can be from various sources, not just your file copy operation.

<details>
  <summary>The underlying issue is explained here</summary>
  
  In Ubuntu, when you copy a large ISO file to a USB drive, the transfer appears to complete quickly due to the operating system's use of caching. Essentially, Ubuntu writes the data first to a cache (a section of your computer's RAM), which is much faster than writing directly to the USB drive. This makes the copying process seem faster.

However, the data in the cache is not immediately written to the USB drive. It's scheduled to be written at a later time when the system deems it efficient. This is why you need to run the sync command. The sync command ensures that all cached data is flushed from the cache and written to the disk (in this case, your USB drive). This process is crucial for ensuring data integrity.

If you remove the USB drive without running sync, there's a risk that not all data has been written to the drive, which could lead to data corruption or incomplete file transfer.

This is what happened here, the iso on the usb key was corrupted.

</details>

**Comment by riordant** [comment]
@tigitz great info, appreciate that.

**Comment by CaioClementino** [comment]
the iso was incomplete. everything works just fine.

Em qui., 2 de mai. de 2024 08:12, tadhg ***@***.***> escreveu:
