### ISSUE TITLE
Gentoo can not boot

### ISSUE THREAD

**Issue by sonichy** [ventoy/Ventoy#779]
https://www.gentoo.org
https://bouncer.gentoo.org/fetch/root/all/releases/amd64/autobuilds/20210228T214502Z/install-amd64-minimal-20210228T214502Z.iso

**Comment by ventoy** [comment]
请详细描述下问题现象，提供下截图或者视频。
我自己在我的笔记本上测试这个ISO文件，Legacy BIOS模式和UEFI模式都可以正常启动。
```
install-amd64-minimal-20210228T214502Z.iso   MD5:495032e3821faecd64ca582493ddebc1
```

**Comment by sonichy** [comment]
复制到U盘的ISO的MD5变了！

**Comment by ventoy** [comment]
那就是复制时出错了。文件大小一个字节都没变，就md5值不一样了？ On 03/03/2021 00:12, 海天鹰 wrote: 

复制到U盘的ISO的MD5变了！



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ventoy/Ventoy/issues/779#issuecomment-789023072",

"url": "https://github.com/ventoy/Ventoy/issues/779#issuecomment-789023072",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by sonichy** [comment]
KDE neon Live Dophin 发送到U盘，关机的时候好像有个进程说是几分钟后结束，我直接reset重启了，然后重启U盘卡了几次。

**Comment by ventoy** [comment]
有没有注意文件不对的时候，文件大小有没有问题？
Ventoy 启动时会检查文件大小，如果文件大小有异常也会告警。
没有告警，我怀疑是不是文件大小还是对的，只是md5对应不上，想确认一下。

**Comment by sonichy** [comment]
大小好像是对的，而且Gentoo的ISO没有Gentoo字样，无法区分，所以我把文件名改成了GentooYYYYMMdd。
你怎么确定文件大小，和官方比对？
启动前检查大小或MD5？
如果是我自己做的ISO呢？
这种开发中的ISO也可以启动：https://dir.omame.tech/cyberos-iso/
