### ISSUE TITLE
Linux arch/Manjaro: can not find grubx64_real.efi and grubia32_real.efi during USB creating

### ISSUE THREAD

**Issue by slrslr** [ventoy/Ventoy#785]
```
5.10.18-1-MANJARO
Name                  : ventoy
Version               : 1.0.35-1
Description           : A new multiboot USB solution
URL                   : http://www.ventoy.net
Licenses              : GPL3
Repository            : community
```

at the end of the following output it can not find grubx64_real.efi and grubia32_real.efi

```
$ sudo ventoy -i -g /dev/sdc

**********************************************
      Ventoy: 1.0.35  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Disk : /dev/sdc
Model: Generic MassStorageClass (scsi)
Size : 29 GB
Style: GPT


Attention:
You will install Ventoy to /dev/sdc.
All the data on the disk /dev/sdc will be lost!!!

Continue? (y/n) y

All the data on the disk /dev/sdc will be lost!!!
Double-check. Continue? (y/n) y

Create partitions on /dev/sdc by parted in GPT style ...
Done
mkfs on disk partitions ...
create efi fat fs /dev/sdc2 ...
mkfs.fat 4.1 (2017-01-24)
success
mkexfatfs 1.3.0
Creating... done.
Flushing... done.
File system created successfully.
writing data to disk ...
sync data ...
esp partition processing ...
mv: cannot stat './tmp_mnt/EFI/BOOT/grubx64_real.efi': No such file or directory
mv: cannot stat './tmp_mnt/EFI/BOOT/grubia32_real.efi': No such file or directory

Install Ventoy to /dev/sdc successfully finished.

```

disk mounted, /run/media/me/VTOYEFI/ moutned also, but does not contain anything. I wanted to let you know.
By the way it was stuck weird long time in phrase "writing data to disk ...", i would expect this be done under 45 seconds, but it was minutes.

**Comment by ventoy** [comment]
Please use the latest 1.0.37 release On 03/06/2021 23:26, slrslr wrote: 
5.10.18-1-MANJARO
Name                  : ventoy
Version               : 1.0.35-1
Description           : A new multiboot USB solution
URL                   : http://www.ventoy.net
Licenses              : GPL3
Repository            : community

at the end of the following output it can not find grubx64_real.efi and grubia32_real.efi
$ sudo ventoy -i -g /dev/sdc

**********************************************
      Ventoy: 1.0.35  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Disk : /dev/sdc
Model: Generic MassStorageClass (scsi)
Size : 29 GB
Style: GPT


Attention:
You will install Ventoy to /dev/sdc.
All the data on the disk /dev/sdc will be lost!!!

Continue? (y/n) y

All the data on the disk /dev/sdc will be lost!!!
Double-check. Continue? (y/n) y

Create partitions on /dev/sdc by parted in GPT style ...
Done
mkfs on disk partitions ...
create efi fat fs /dev/sdc2 ...
mkfs.fat 4.1 (2017-01-24)
success
mkexfatfs 1.3.0
Creating... done.
Flushing... done.
File system created successfully.
writing data to disk ...
sync data ...
esp partition processing ...
mv: cannot stat './tmp_mnt/EFI/BOOT/grubx64_real.efi': No such file or directory
mv: cannot stat './tmp_mnt/EFI/BOOT/grubia32_real.efi': No such file or directory

Install Ventoy to /dev/sdc successfully finished.


disk mounted, /run/media/me/VTOYEFI/ moutned also, but does not contain anything. I wanted to let you know.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/785",
"url": "https://github.com/ventoy/Ventoy/issues/785",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by slrslr** [comment]
I have installed it: pamac build ventoy-bin
It installed: 1.0.37-2
$ sudo ventoy -u -g /dev/sdc
```
/dev/sdc does not contain Ventoy or data corrupted
Please use -i option if you want to install ventoy to /dev/sdc
```
:-/
sudo ventoy -i -g /dev/sdc
worked, VTOYEFI contains the data. Thank you, i like Ventoy.
