### ISSUE TITLE
VTOY_DEFAULT_KBD_LAYOUT parameter problem

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#832]
hi admin!

I have added this line to **ventoy.json** file  ( https://www.ventoy.net/en/plugin_control.html )

{ "VTOY_DEFAULT_KBD_LAYOUT": "TURKISH_Q" }

but default kayboard layout can not change...so I can not write some turkish characters (**ş,ç,ö,ü,ğ,ı**) from console screen...
I captured a video about my problem... 
https://vimeo.com/533550004

how can I fix my problem?

ventoy.json file link :  https://easyupload.io/c2l04x

**Comment by ventoy** [comment]
Does it work if you use F5 to change the the keyboard layout? On 04/06/2021 22:12, Tayfun Akkoyun wrote: 

hi admin!

I have added this line to ventoy.json file  ( https://www.ventoy.net/en/plugin_control.html )

{ "VTOY_DEFAULT_KBD_LAYOUT": "TURKISH_Q" }

but default kayboard layout can not change...so I can not write some turkish characters (ş,ç,ö,ü,ğ,ı) from console screen...

I captured a video about my problem...

https://vimeo.com/manage/videos/533550004

how can I fix my problem?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ventoy/Ventoy/issues/832",

"url": "https://github.com/ventoy/Ventoy/issues/832",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by crasadure** [comment]
> Does it work if you use F5 to change the the keyboard layout? 

F5 change the keyboard layout function doesn't work. I tried it at my captured video.

**Comment by ventoy** [comment]
This feature is transplant from [agFM](https://github.com/a1ive/grub2-filemanager) and it seems that it just make some keymap about some symbol (^=-...)
