### ISSUE TITLE
Ventoy Zorin OS support

### ISSUE THREAD

**Issue by Sayor0630** [ventoy/Ventoy#952]
Doesn't Ventoy support Zorin OS? I have downloaded Zorin OS core and copied it to Ventoy but Zorin OS isn't showing on the boot screen. What can I do?
![image](https://user-images.githubusercontent.com/77576588/121486101-a906dd00-c9f2-11eb-9fc8-2f4553cdb410.png)

**Comment by steve6375** [comment]
Does the checksum (CRC32, SHA1 etc.) on the USB drive match the file on your hard drive?

**Comment by Sayor0630** [comment]
Yes

**Comment by steve6375** [comment]
Try renaming the /vento/ventoy.json file to see if that is causing a problem.
Otherwise, try making a Ventoy drive using a different USB drive and just put the one Zorin ISO on it.

**Comment by Sayor0630** [comment]
it's already renamed
![image](https://user-images.githubusercontent.com/77576588/121487846-50384400-c9f4-11eb-92fd-b48ca26ab427.png)

**Comment by Sayor0630** [comment]
I can't see Zorin OS here
![image](https://user-images.githubusercontent.com/77576588/121488286-c0df6080-c9f4-11eb-9f0f-1e976b0c1fd9.png)

**Comment by steve6375** [comment]
I mean remove  ventoy.json so it is not used.
And try a different fresh USB drive. AFAIK Ventoy should list all .iso files.

**Comment by Sayor0630** [comment]
My this ventoy is for custom themes.

**Comment by steve6375** [comment]
This is a test to see what could be causing the problem. Since you are **sure** the checksum of the file is correct, it does not appear to be a problem with your USB drive. So that leaves the Ventoy.json file. By temporarily removing the Ventoy.json file we can see if the problem goes away or remains. Do you understand?
And by using a different USB drive with a new Ventoy install and just the one Zorin ISO, we can see if there is something strange about your first USB drive. Again this is a test or experiment. Do you understand the concept?

**Comment by Sayor0630** [comment]
Yeah. yhanks. trying

**Comment by steve6375** [comment]
P.S. You are scrolling down in the menu?

**Comment by Sayor0630** [comment]
Zorin OS detected in boot after removing the ventoy folder

**Comment by steve6375** [comment]
Maybe your theme only shows 6 isos per screen?

**Comment by Sayor0630** [comment]
Aaah. Sorry. It was on the next scroll. Sorry for wasting your time. And thank you very much.
