### ISSUE TITLE
Venty on Centos 7.3

### ISSUE THREAD

**Issue by yyu0378** [ventoy/Ventoy#966]
Ventoy version:1.0.46 x86_64
OS version:Centos 7.3 x86_64
Parted version:3.0.1
Run command: ./Ventoy2Disk.sh -I -r 100 -s -g /dev/sdb
Will show one error:
parted: invalid token: msftdata
![ventoy-1](https://user-images.githubusercontent.com/2733175/122526783-409ca900-d04d-11eb-9c52-2c18136e98ba.jpg)
Ventoy can not support centos 7.3?

**Comment by ventoy** [comment]
Ventoy2Disk.sh use `set msftdata on` with parted when you use GPT partition style (with -g).
So the parted need to be `3.1.90+` if you select GPT partition style.
Alough it report this error, it can work well in most cases. Only if you try to install Windows in UEFI mode it will run into problem.
Because Windows doesn't allow two EFI partitions in the system.

You can try Ventoy Linux GUI: https://www.ventoy.net/en/doc_linux_webui.html
Or you can use MBR partition style with can also support both Legacy BIOS mode and UEFI mode.
Or you can update the parted in your system.

**Comment by yyu0378** [comment]
Thank you,guys.
